import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:fx_core/fx_core.dart';
import 'package:path/path.dart' as p;

import '../output/output_formatter.dart';
import 'run_command.dart';

/// `fx configure-ai-agents` — Generate AI agent configuration files.
///
/// Creates workspace-aware rule/instruction files for AI coding assistants
/// (Claude, Codex, Copilot, Cursor, Gemini, OpenCode).
class ConfigureAiAgentsCommand extends Command<void> {
  final OutputFormatter formatter;

  @override
  String get name => 'configure-ai-agents';

  @override
  String get description =>
      'Generate AI agent configuration files with workspace context.';

  ConfigureAiAgentsCommand({required this.formatter}) {
    argParser
      ..addOption(
        'agents',
        help:
            'Comma-separated list of agents to configure (default: all).\n'
            'Supported: claude, codex, copilot, cursor, gemini, opencode',
      )
      ..addFlag(
        'check',
        help: 'Validate existing configs are up-to-date (exit 1 if stale).',
        negatable: false,
      )
      ..addFlag(
        'interactive',
        help: 'Prompt before writing each file.',
        defaultsTo: true,
      )
      ..addOption(
        'workspace',
        help: 'Path to workspace root (for testing).',
        hide: true,
      );
  }

  @override
  Future<void> run() async {
    final workspacePath = argResults!['workspace'] as String?;
    final agentsArg = argResults!['agents'] as String?;
    final checkMode = argResults!['check'] as bool;

    final wsRoot = workspacePath ?? _findWorkspaceRoot();
    final workspace = await WorkspaceLoader.load(wsRoot);

    final selectedAgents = agentsArg != null
        ? agentsArg.split(',').map((s) => s.trim().toLowerCase()).toList()
        : _allAgentNames;

    final content = _generateContent(workspace);
    final configs = _agentConfigs(
      wsRoot,
    ).where((c) => selectedAgents.contains(c.name)).toList();

    if (checkMode) {
      var staleCount = 0;
      for (final config in configs) {
        final file = File(config.filePath);
        if (!file.existsSync()) {
          formatter.writeln('  MISSING: ${config.name} (${config.filePath})');
          staleCount++;
        } else {
          final existing = file.readAsStringSync();
          if (existing != content) {
            formatter.writeln('  STALE: ${config.name} (${config.filePath})');
            staleCount++;
          }
        }
      }
      if (staleCount > 0) {
        formatter.writeln(
          '\n$staleCount config(s) need updating. Run `fx configure-ai-agents` to fix.',
        );
        throw ProcessExit(1);
      }
      formatter.writeln('All AI agent configs are up-to-date.');
      return;
    }

    for (final config in configs) {
      final file = File(config.filePath);
      await file.parent.create(recursive: true);
      await file.writeAsString(content);
      formatter.writeln('  Wrote ${config.name}: ${config.filePath}');
    }

    formatter.writeln(
      '\nConfigured ${configs.length} AI agent(s). '
      'Run with --check to validate.',
    );
  }

  String _generateContent(Workspace workspace) {
    final buf = StringBuffer();
    buf.writeln('# Fx Workspace — AI Agent Context');
    buf.writeln();
    buf.writeln(
      'This file is auto-generated by `fx configure-ai-agents`. '
      'Do not edit manually.',
    );
    buf.writeln();

    // Workspace overview
    buf.writeln('## Workspace Structure');
    buf.writeln();
    buf.writeln(
      'This is a Dart/Flutter monorepo managed by **fx** '
      '(similar to Nx for JS/TS).',
    );
    buf.writeln();

    // Projects
    buf.writeln('### Projects');
    buf.writeln();
    for (final project in workspace.projects) {
      final deps = project.dependencies.isNotEmpty
          ? ' (depends on: ${project.dependencies.join(', ')})'
          : '';
      buf.writeln('- **${project.name}** — ${project.type.toJson()}$deps');
    }
    buf.writeln();

    // Targets
    buf.writeln('### Available Targets');
    buf.writeln();
    for (final entry in workspace.config.targets.entries) {
      final target = entry.value;
      final deps = target.dependsOn.isNotEmpty
          ? ' (depends on: ${target.dependsOn.join(', ')})'
          : '';
      buf.writeln('- **${entry.key}**: `${target.executor}`$deps');
    }
    buf.writeln();

    // CLI usage
    buf.writeln('## fx CLI Commands');
    buf.writeln();
    buf.writeln('```bash');
    buf.writeln('# Run a target on a single project');
    buf.writeln('fx run <project> <target>');
    buf.writeln();
    buf.writeln('# Run a target on all projects');
    buf.writeln('fx run-many --target=<target>');
    buf.writeln();
    buf.writeln('# Run on affected projects only (since git base)');
    buf.writeln('fx affected --target=<target>');
    buf.writeln();
    buf.writeln('# List all projects');
    buf.writeln('fx list');
    buf.writeln();
    buf.writeln('# View dependency graph');
    buf.writeln('fx graph');
    buf.writeln();
    buf.writeln('# Generate a new package');
    buf.writeln('fx generate dart_package <name>');
    buf.writeln();
    buf.writeln('# Bootstrap (install all deps)');
    buf.writeln('fx bootstrap');
    buf.writeln('```');
    buf.writeln();

    // Dependency graph summary
    buf.writeln('## Dependency Overview');
    buf.writeln();
    final hasDependent = workspace.projects.any(
      (p) => p.dependencies.isNotEmpty,
    );
    if (hasDependent) {
      for (final project in workspace.projects) {
        if (project.dependencies.isNotEmpty) {
          buf.writeln('- ${project.name} → ${project.dependencies.join(', ')}');
        }
      }
    } else {
      buf.writeln('No inter-project dependencies.');
    }
    buf.writeln();

    return buf.toString();
  }

  static const _allAgentNames = [
    'claude',
    'codex',
    'copilot',
    'cursor',
    'gemini',
    'opencode',
  ];

  List<_AgentConfig> _agentConfigs(String wsRoot) => [
    _AgentConfig(
      name: 'claude',
      filePath: p.join(wsRoot, '.claude', 'rules', 'fx-workspace.md'),
    ),
    _AgentConfig(name: 'codex', filePath: p.join(wsRoot, 'codex.md')),
    _AgentConfig(
      name: 'copilot',
      filePath: p.join(wsRoot, '.github', 'copilot-instructions.md'),
    ),
    _AgentConfig(name: 'cursor', filePath: p.join(wsRoot, '.cursorrules')),
    _AgentConfig(
      name: 'gemini',
      filePath: p.join(wsRoot, '.gemini', 'rules', 'fx-workspace.md'),
    ),
    _AgentConfig(
      name: 'opencode',
      filePath: p.join(wsRoot, '.opencode', 'rules', 'fx-workspace.md'),
    ),
  ];

  String _findWorkspaceRoot() {
    final root = FileUtils.findWorkspaceRoot(Directory.current.path);
    if (root == null) {
      throw UsageException(
        'Not inside an fx workspace. Run `fx init` first.',
        usage,
      );
    }
    return root;
  }
}

class _AgentConfig {
  final String name;
  final String filePath;

  const _AgentConfig({required this.name, required this.filePath});
}
